### ISSUE TITLE
Lab server complains about nodejs missing

### ISSUE THREAD

**Issue by LillyWho** [tiliaqt/transkit#3]
> `[E 20:50:42.343 LabApp] Uncaught exception GET /lab/api/extensions?1630781442326 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/lab/api/extensions?1630781442326', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 221, in get
        extensions = yield self.manager.list_extensions()
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 91, in list_extensions
        pkg_info = yield self._get_pkg_info(name, data)
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 160, in _get_pkg_info
        outdated = yield self._get_outdated()
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 221, in get
        extensions = yield self.manager.list_extensions()
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 91, in list_extensions
        pkg_info = yield self._get_pkg_info(name, data)
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 160, in _get_pkg_info
        outdated = yield self._get_outdated()
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 221, in get
        extensions = yield self.manager.list_extensions()
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 221, in get
        extensions = yield self.manager.list_extensions()
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 91, in list_extensions
        pkg_info = yield self._get_pkg_info(name, data)
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 91, in list_extensions
        pkg_info = yield self._get_pkg_info(name, data)
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 160, in _get_pkg_info
        outdated = yield self._get_outdated()
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 160, in _get_pkg_info
        outdated = yield self._get_outdated()
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 191, in _load_outdated
        data = yield self.executor.submit(
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 438, in result
        return self.__get_result()
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
        raise self._exception
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/jupyterlab/commands.py", line 541, in get_latest_compatible_package_versions
        return handler.latest_compatible_package_versions(names)
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/jupyterlab/commands.py", line 1679, in latest_compatible_package_versions
        ret = self._run([which('npm'), 'pack'] + keys, cwd=tempdir)
      File "/Users/lilly/Library/Caches/pypoetry/virtualenvs/transkit-4cxFeUt3-py3.9/lib/python3.9/site-packages/jupyterlab_server/process.py", line 59, in which
        raise ValueError(msg)
    ValueError: Please install Node.js and npm before continuing installation. You may be able to install Node.js from your package manager, from conda, or directly from the Node.js website (https://nodejs.org).
[W 20:50:42.346 LabApp] Unhandled error`

Just for testing I installed  nodejs16 from MacPorts, no difference.

**Comment by bananafeet26** [comment]
Sorry to post here. I'm using both of your code in my metabolite tracker.

Just the math section. I'm using to plot metabolites of exogenous testosterone (DHT, E2).

To be honest I don't understand the math. But it seems to work.

Anyway is it ok to use your code? Do you want any attribution/copyright etc

**Comment by violetele** [comment]
@bananafeet26 That’s great that this code has been useful! Over the weekend I’ll add a license and fix whatever build issues are going on.

**Comment by bananafeet26** [comment]
> [@bananafeet26](https://github.com/bananafeet26) That’s great that this code has been useful! Over the weekend I’ll add a license and fix whatever build issues are going on.


Are you the math genius who made the 3 compartment model? I'm struggling to understand the mathematics.

I'm guessing that the D is a scaling factor. Kind of like bioavailability in the tmax/cmax Bateman calculations.

But I want to know how you derived the k1, k2 and k3?

Is there a way I can make these K values for various testosterone esters? I am currently trying to derive my Bateman model t1/2, cmax and tmax so I can use the algorithm you came up with for the modeler.

I know that basically these numbers just describe a curve. I can get volume of distribution data for testosterone esters. But I don't know how to plug that into your model because you use D not Vd.

I noticed your models have slightly slower decay that for the natural models. Maybe I'm implementing the model incorrectly.

I think your model uses pg/mL. 

As I said I'm not good at mathematics. But I think even this is kind of a specialist area.

**Comment by violetele** [comment]
Ok, I've fixed the build issues and updated all of the dependencies so this should all be working again. Thanks for the report @LillyWho.

@bananafeet26 I would have sworn I committed the derivation of the model parameters, but it's been a long time and I guess I didn't. Cmpt3VModel and Cmpt4VModel are models that I derived using Mathematica. I think they are more or less equivalent to more standard presentations of compartmental models but the various parameters are simplified into just `k1`, `k2`, `k3` for ease of numeric optimization (so they aren't over-determined). In the differential equations, `D` is the initial does, and the `k`s are rate constants between the compartments. These constants don't necessarily have a clear intuitive physical meaning, but as long as we are starting from a curve of actual measured blood levels over time, we don't have to care.

To actually calculate them you can just call, for example: `Cmpt3VModel().fit(<ndarray of data>)`. Then using the parameters it spits out, create your dose response functions just like in `medications.py`. I'm pretty sure the parameters currently in that file are derived from the Oriowo 1980 study.

All that said it's been a while so I've probably forgotten some of the details. [Aly used the models I derived in her meta-analysis](https://transfemscience.org/articles/injectable-e2-meta-analysis/) and the last time I was working on this, I think my plan was to standardize on the curve parameters that she had derived using data from many research studies.

You are welcome to create a new issue to discuss more. I am in a very different place in my life from 5 years ago (almost all better), so time permitting I'm open to doing some more work on this.
